# Generated by Django 3.1.4 on 2020-12-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateTimeField()),
                ('dia', models.CharField(max_length=50)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('grupo', models.CharField(max_length=50)),
                ('profesor', models.CharField(max_length=50)),
            ],
        ),
    ]
